---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-14.04
  run_list:
  - recipe[apt]
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
- name: centos-6.6
  run_list:
  - recipe[yum-epel]
- name: centos-7.1
  run_list:
  - recipe[yum-epel]
suites:
- name: default
  run_list:
  - recipe[hubot]
  attributes: {}
- name: supervisor
  run_list:
  - recipe[hubot]
  attributes:
    hubot:
      daemon: supervisor
